twig:
    globals:
        main_color: '%env(MAIN_COLOR)%'
        logo_image: '%env(LOGO_IMAGE)%'
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
